"""Detection signals for Provenance Guard.

Milestone 3 implements Signal 1 (LLM classifier via Groq). Signal 2 (stylometric
heuristics) is specified in planning.md and lands in Milestone 4.
"""

import os
import json

from groq import Groq

_MODEL = os.getenv("GROQ_MODEL", "llama-3.3-70b-versatile")

_SYSTEM_PROMPT = (
    "You are a forensic text-provenance classifier. Given a passage, judge how "
    "likely it was generated by an AI language model versus written by a human. "
    "Consider tone, coherence, hedging, register uniformity, and idiosyncrasy. "
    "Respond ONLY with a compact JSON object of the form "
    '{"ai_likelihood": <float 0..1>, "rationale": "<one short sentence>"} '
    "where 0 means confidently human and 1 means confidently AI-generated."
)


def _clamp(x: float) -> float:
    return max(0.0, min(1.0, float(x)))


def groq_signal(text: str) -> dict:
    """Signal 1: ask Groq to assess AI-likelihood.

    Returns a dict: {"ai_likelihood": float in [0,1], "rationale": str,
                     "ok": bool}. On any API/parse failure, returns a neutral
    0.5 with ok=False so the pipeline degrades gracefully rather than crashing.
    """
    api_key = os.getenv("GROQ_API_KEY")
    if not api_key:
        return {"ai_likelihood": 0.5, "rationale": "GROQ_API_KEY not set.", "ok": False}

    try:
        client = Groq(api_key=api_key)
        completion = client.chat.completions.create(
            model=_MODEL,
            temperature=0,
            max_tokens=150,
            response_format={"type": "json_object"},
            messages=[
                {"role": "system", "content": _SYSTEM_PROMPT},
                {"role": "user", "content": text},
            ],
        )
        raw = completion.choices[0].message.content
        parsed = json.loads(raw)
        return {
            "ai_likelihood": _clamp(parsed.get("ai_likelihood", 0.5)),
            "rationale": str(parsed.get("rationale", "")).strip(),
            "ok": True,
        }
    except Exception as exc:  # network, parse, auth, etc.
        return {
            "ai_likelihood": 0.5,
            "rationale": f"LLM signal unavailable: {exc}",
            "ok": False,
        }


if __name__ == "__main__":
    # Quick standalone test — call the signal directly before wiring the route.
    from dotenv import load_dotenv

    load_dotenv()
    samples = {
        "human-ish": (
            "Ugh, the bus was late again so I just walked. Rained the whole way, "
            "of course. Got a coffee to make up for it — worth it, barely."
        ),
        "ai-ish": (
            "In today's fast-paced world, effective time management is essential. "
            "By prioritizing tasks and setting clear goals, individuals can enhance "
            "productivity and achieve a healthy work-life balance."
        ),
    }
    for name, sample in samples.items():
        print(name, "->", groq_signal(sample))
